# Generated by Django 3.2.5 on 2021-07-22 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskType',
            fields=[
                ('si_no', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=15)),
                ('parent_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
