# Generated by Django 3.2.5 on 2021-07-21 17:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25, unique=True, validators=[django.core.validators.RegexValidator('^[aA].{0,}[01]$', 'Username should start with a/A and end with 0/1')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_title', models.CharField(max_length=200)),
                ('task_description', models.CharField(blank=True, max_length=2000)),
                ('task_pic', models.ImageField(null=True, upload_to='uploads/')),
                ('create_time_stamp', models.DateTimeField(auto_now_add=True)),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task1.user1')),
            ],
        ),
    ]
